AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  paymentProcessor:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: cmd/api/main.go
      Handler: main
      Runtime: go1.x
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /payment-processor
            Method: PATCH

  paymentsSQS:
    Type: 'AWS::SQS::Queue'

  paymentsProcessor:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: cmd/api/main.go
      Handler: main
      Runtime: go1.x
      Events:
        MySqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt paymentsSQS.Arn
